services:
  - type: web
    name: money-seed
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: money-seed-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.10

databases:
  - name: money-seed-db
    databaseName: moneyseed
    user: moneyseed
    plan: free
